---
title: "limiares"
output: html_document
---

```{r setup, include=FALSE, results="asis", echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, warn.conflicts = FALSE)
library(venn)
library(stringr)
library(knitr)
library(ggplot2)
logs <- data.frame(sistema=c("Allegro", "SDL","SFML","Coco2dx"), caminho = c('~/bib/log_allegro.R', '~/bib/log_SDL.R', '~/bib/log_SFML.R', '~/bib/log_coco2dx.R'),ws_analise=c('~/bib/analise_allegro.RData', '~/bib/analise_SDL.RData', '~/bib/analise_SFML.RData', '~/bib/analise_coco2dx.RData'), ws_analisetemporal = c('~/bib/analisetemporal_allegro.RData', '~/bib/analisetemporal_SDL.RData', '~/bib/analisetemporal_SFML.RData', '~/bib/analisetemporal_coco2dx.RData'), ws_analisetemporaljanela = c('~/bib/analisetemporaljanela_allegro.RData', '~/bib/analisetemporaljanela_SDL.RData', '~/bib/analisetemporaljanela_SFML.RData', '~/bib/analisetemporaljanela_coco2dx.RData')  )
load ("analise_allegro.RData")
```



```{r results="asis", echo=FALSE,message=FALSE,warning=FALSE}
for (it in 1:length(logs$sistema)){
  aux<-it
  #cat("  \n###",  as.character( logs$sistema[it] ) ,"\n")
  rm(list = ls()[!ls() %in% c("logs","it")])
  #source(as.character(logs$caminho[it]) , verbose=FALSE)
  #source( '~/bib/analise.R', echo=FALSE, verbose=FALSE, prompt.echo=FALSE)
  load (as.character(logs$ws_analisetemporaljanela[it]))


    
        cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.1") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  esp <- esp_bind2%>% filter(prob==0.1)  
  gen <-gen_bind2%>% filter(prob==0.1)  

 
  par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(esp$iteracao,esp$porc,col="red",type = "l",ylim = c(0,100), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(gen$iteracao,gen$porc,col="green",type = "l" )
  legend("top",c("Especialista", "Generalista"), col=c("red","green"),lty=1)

  
        cat("\n")
        
        
        
         cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.2") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")       
        
    esp <- esp_bind2%>% filter(prob==0.2)     
  gen <-gen_bind2%>% filter(prob==0.2)  

 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(esp$iteracao,esp$porc,col="red",type = "l",ylim = c(0,100), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(gen$iteracao,gen$porc,col="green",type = "l" )
  legend("top",c("Especialista", "Generalista"), col=c("red","green"),lty=1)

  
        cat("\n")      
        
           cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.3") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        
     esp <- esp_bind2%>% filter(prob==0.3)     
  gen <-gen_bind2%>% filter(prob==0.3)  
  
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(esp$iteracao,esp$porc,col="red",type = "l",ylim = c(0,100), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(gen$iteracao,gen$porc,col="green",type = "l" )
  legend("top",c("Especialista", "Generalista"), col=c("red","green"),lty=1)

  
        cat("\n")     
        
            cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.4") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")    
        
         esp <- esp_bind2%>% filter(prob==0.4)     
  gen <-gen_bind2%>% filter(prob==0.4)  
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(esp$iteracao,esp$porc,col="red",type = "l",ylim = c(0,100), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(gen$iteracao,gen$porc,col="green",type = "l" )
  legend("top",c("Especialista", "Generalista"), col=c("red","green"),lty=1)

  
        cat("\n") 
        
         cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.5") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")       
        
    esp <- esp_bind2%>% filter(prob==0.5)     
  gen <-gen_bind2%>% filter(prob==0.5)  
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(esp$iteracao,esp$porc,col="red",type = "l",ylim = c(0,100), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(gen$iteracao,gen$porc,col="green",type = "l" )
  legend("top",c("Especialista", "Generalista"), col=c("red","green"),lty=1)

  
        cat("\n")      
        

        

    
}
```

