---
title: "limiares"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, warn.conflicts = FALSE)
library(venn)
library(stringr)
library(knitr)
library(ggplot2)
logs <- data.frame(sistema=c("Allegro", "SDL","SFML","Coco2dx"), caminho = c('~/bib/log_allegro.R', '~/bib/log_SDL.R', '~/bib/log_SFML.R', '~/bib/log_coco2dx.R'),ws_analise=c('~/bib/analise_allegro.RData', '~/bib/analise_SDL.RData', '~/bib/analise_SFML.RData', '~/bib/analise_coco2dx.RData'), ws_analisetemporal = c('~/bib/analisetemporal_allegro.RData', '~/bib/analisetemporal_SDL.RData', '~/bib/analisetemporal_SFML.RData', '~/bib/analisetemporal_coco2dx.RData'), ws_analisetemporaljanela = c('~/bib/analisetemporaljanela_allegro.RData', '~/bib/analisetemporaljanela_SDL.RData', '~/bib/analisetemporaljanela_SFML.RData', '~/bib/analisetemporaljanela_coco2dx.RData')  )
load ("analise_allegro.RData")
```



```{r cars}
for (it in 1:length(logs$sistema)){
  #aux<-it
  #cat("  \n###",  as.character( logs$sistema[it] ) ,"\n")
  rm(list = ls()[!ls() %in% c("logs","it")])
  #source(as.character(logs$caminho[it]) , verbose=FALSE)
  #source( '~/bib/analise.R', echo=FALSE, verbose=FALSE, prompt.echo=FALSE)
  load (as.character(logs$ws_analise[it]))
 #load ("analise_allegro.RData")


 for (itx in 1:length(prob)){
       cat( as.character( logs$sistema[it] ) ,"\n")
       cat("\n",  as.character( prob[itx] ) ,"\n")
    x<-x2%>% filter(prob==as.numeric(prob[itx])) %>%
      ungroup()%>%
      select(mobile,indd,desktop)
    venn(x)
    }

}
```

