---
title: "limiares"
output: html_document
---

```{r setup, include=FALSE, results="asis", echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, warn.conflicts = FALSE)
library(venn)
library(stringr)
library(knitr)
library(ggplot2)
library(trend)
# Create variable 'log'  that contains the paths of the scripts and workspaces (.RData)
  source("~/bib/paths.R")
```



```{r results="asis", echo=FALSE,message=FALSE,warning=FALSE}
for (it in 1:length(logs$sistema)){
  aux<-it
  #cat("  \n###",  as.character( logs$sistema[it] ) ,"\n")
  rm(list = ls()[!ls() %in% c("logs","it")])
  #source(as.character(logs$caminho[it]) , verbose=FALSE)
  #source( '~/bib/analise.R', echo=FALSE, verbose=FALSE, prompt.echo=FALSE)
  load (as.character(logs$ws_analisetemporaljanela[it]))


    
        cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.1") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo (Desktop Mobile)  \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  mobile <- mobile_bind%>% filter(prob==0.1)     
  desktop <-desktop_bind%>% filter(prob==0.1)  
  mobiledesktop <- desktopmobile_bind%>% filter(prob==0.1)   
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(mobile$iteracao,mobile$porc,col="red",type = "l",ylim = c(0,100),xlim=c(1,j), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(desktop$iteracao,desktop$porc,col="green",type = "l" )
  lines(mobiledesktop$iteracao,mobiledesktop$porc,col="black",type = "l" )
  legend("top",c("Mobile", "Desktop", "Desktop Mobile"), col=c("red","green","black"),lty=1)

  if (length(mobile$porc)< 3){
    mobiletwo<-data.frame(p.value=99)
     mobileup<-data.frame(p.value=99)
      mobiledown<-data.frame(p.value=99)
  }else{
 mobiletwo <- mk.test(mobile$porc, alternative = c("two.sided"), continuity = TRUE)
 mobileup <- mk.test(mobile$porc, alternative = c("greater"), continuity = TRUE)
 mobiledown <- mk.test(mobile$porc, alternative = c("less"), continuity = TRUE)
  }
 desktoptwo <- mk.test(desktop$porc, alternative = c("two.sided"), continuity = TRUE)
 desktopup <- mk.test(desktop$porc, alternative = c("greater"), continuity = TRUE)
 desktopdown <- mk.test(desktop$porc, alternative = c("less"), continuity = TRUE)
 mobiledesktoptwo <- mk.test(mobiledesktop$porc, alternative = c("two.sided"), continuity = TRUE)
 mobiledesktopnup <- mk.test(mobiledesktop$porc, alternative = c("greater"), continuity = TRUE)
mobiledesktopdown <- mk.test(mobiledesktop$porc, alternative = c("less"), continuity = TRUE)
aux<-data.frame(mobile = c(as.numeric(mobiletwo["p.value"]),as.numeric(mobileup["p.value"]),as.numeric(mobiledown["p.value"])),
               desktop = c(as.numeric(desktoptwo["p.value"]),as.numeric(desktopup["p.value"]),as.numeric(desktopdown["p.value"])),
               mobiledesktop = c(as.numeric(mobiledesktoptwo["p.value"]),as.numeric(mobiledesktopnup["p.value"]),as.numeric(mobiledesktopdown["p.value"])),
               row.names = c("twosided", "greater", "less"))
 
   print(kable(aux)) 
        cat("\n")
        
        

        
        
        
        
        
        
         cat("\n\n####",  as.character( logs$sistema[it] ),"\n")
         cat("\n",  as.character( "0.2") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo (Desktop Mobile)  \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  mobile <- mobile_bind%>% filter(prob==0.2)     
  desktop <-desktop_bind%>% filter(prob==0.2)  
  mobiledesktop <- desktopmobile_bind%>% filter(prob==0.2)   
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(mobile$iteracao,mobile$porc,col="red",type = "l",ylim = c(0,100), xlim=c(1,j),xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(desktop$iteracao,desktop$porc,col="green",type = "l" )
  lines(mobiledesktop$iteracao,mobiledesktop$porc,col="black",type = "l" )
  legend("top",c("Mobile", "Desktop", "Desktop Mobile"), col=c("red","green","black"),lty=1)

  if (length(mobile$porc)< 3){
    mobiletwo<-data.frame(p.value=99)
     mobileup<-data.frame(p.value=99)
      mobiledown<-data.frame(p.value=99)
  }else{
 mobiletwo <- mk.test(mobile$porc, alternative = c("two.sided"), continuity = TRUE)
 mobileup <- mk.test(mobile$porc, alternative = c("greater"), continuity = TRUE)
 mobiledown <- mk.test(mobile$porc, alternative = c("less"), continuity = TRUE)
  }

 desktoptwo <- mk.test(desktop$porc, alternative = c("two.sided"), continuity = TRUE)
 desktopup <- mk.test(desktop$porc, alternative = c("greater"), continuity = TRUE)
 desktopdown <- mk.test(desktop$porc, alternative = c("less"), continuity = TRUE)
 mobiledesktoptwo <- mk.test(mobiledesktop$porc, alternative = c("two.sided"), continuity = TRUE)
 mobiledesktopnup <- mk.test(mobiledesktop$porc, alternative = c("greater"), continuity = TRUE)
mobiledesktopdown <- mk.test(mobiledesktop$porc, alternative = c("less"), continuity = TRUE)
aux<-data.frame(mobile = c(as.numeric(mobiletwo["p.value"]),as.numeric(mobileup["p.value"]),as.numeric(mobiledown["p.value"])),
               desktop = c(as.numeric(desktoptwo["p.value"]),as.numeric(desktopup["p.value"]),as.numeric(desktopdown["p.value"])),
               mobiledesktop = c(as.numeric(mobiledesktoptwo["p.value"]),as.numeric(mobiledesktopnup["p.value"]),as.numeric(mobiledesktopdown["p.value"])),
               row.names = c("twosided", "greater", "less"))
 
   print(kable(aux)) 
        cat("\n")               
 
   
        
        
        
        
        
        
        
        
                cat("\n\n####",  as.character( logs$sistema[it] ) , "\n")
         cat("\n",  as.character( "0.3") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo (Desktop Mobile)  \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  mobile <- mobile_bind%>% filter(prob==0.3)     
  desktop <-desktop_bind%>% filter(prob==0.3)  
  mobiledesktop <- desktopmobile_bind%>% filter(prob==0.3)   
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(mobile$iteracao,mobile$porc,col="red",type = "l",ylim = c(0,100), xlim=c(1,j), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(desktop$iteracao,desktop$porc,col="green",type = "l" )
  lines(mobiledesktop$iteracao,mobiledesktop$porc,col="black",type = "l" )
  legend("top",c("Mobile", "Desktop", "Desktop Mobile"), col=c("red","green","black"),lty=1)

  if (length(mobile$porc)< 3){
    mobiletwo<-data.frame(p.value=99)
     mobileup<-data.frame(p.value=99)
      mobiledown<-data.frame(p.value=99)
  }else{
 mobiletwo <- mk.test(mobile$porc, alternative = c("two.sided"), continuity = TRUE)
 mobileup <- mk.test(mobile$porc, alternative = c("greater"), continuity = TRUE)
 mobiledown <- mk.test(mobile$porc, alternative = c("less"), continuity = TRUE)
  }
 desktoptwo <- mk.test(desktop$porc, alternative = c("two.sided"), continuity = TRUE)
 desktopup <- mk.test(desktop$porc, alternative = c("greater"), continuity = TRUE)
 desktopdown <- mk.test(desktop$porc, alternative = c("less"), continuity = TRUE)
 mobiledesktoptwo <- mk.test(mobiledesktop$porc, alternative = c("two.sided"), continuity = TRUE)
 mobiledesktopnup <- mk.test(mobiledesktop$porc, alternative = c("greater"), continuity = TRUE)
mobiledesktopdown <- mk.test(mobiledesktop$porc, alternative = c("less"), continuity = TRUE)
aux<-data.frame(mobile = c(as.numeric(mobiletwo["p.value"]),as.numeric(mobileup["p.value"]),as.numeric(mobiledown["p.value"])),
               desktop = c(as.numeric(desktoptwo["p.value"]),as.numeric(desktopup["p.value"]),as.numeric(desktopdown["p.value"])),
               mobiledesktop = c(as.numeric(mobiledesktoptwo["p.value"]),as.numeric(mobiledesktopnup["p.value"]),as.numeric(mobiledesktopdown["p.value"])),
               row.names = c("twosided", "greater", "less"))
 
   print(kable(aux)) 
        cat("\n") 
        
        
        
        
        
        
        
        
        
        
                cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.4") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo (Desktop Mobile)  \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  mobile <- mobile_bind%>% filter(prob==0.4)     
  desktop <-desktop_bind%>% filter(prob==0.4)  
  mobiledesktop <- desktopmobile_bind%>% filter(prob==0.4)   
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(mobile$iteracao,mobile$porc,col="red",type = "l",ylim = c(0,100),xlim=c(1,j), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(desktop$iteracao,desktop$porc,col="green",type = "l" )
  lines(mobiledesktop$iteracao,mobiledesktop$porc,col="black",type = "l" )
  legend("top",c("Mobile", "Desktop", "Desktop Mobile"), col=c("red","green","black"),lty=1)

     if (length(mobile$porc)< 3){
    mobiletwo<-data.frame(p.value=99)
     mobileup<-data.frame(p.value=99)
      mobiledown<-data.frame(p.value=99)
  }else{
 mobiletwo <- mk.test(mobile$porc, alternative = c("two.sided"), continuity = TRUE)
 mobileup <- mk.test(mobile$porc, alternative = c("greater"), continuity = TRUE)
 mobiledown <- mk.test(mobile$porc, alternative = c("less"), continuity = TRUE)
  }
 desktoptwo <- mk.test(desktop$porc, alternative = c("two.sided"), continuity = TRUE)
 desktopup <- mk.test(desktop$porc, alternative = c("greater"), continuity = TRUE)
 desktopdown <- mk.test(desktop$porc, alternative = c("less"), continuity = TRUE)
 mobiledesktoptwo <- mk.test(mobiledesktop$porc, alternative = c("two.sided"), continuity = TRUE)
 mobiledesktopnup <- mk.test(mobiledesktop$porc, alternative = c("greater"), continuity = TRUE)
mobiledesktopdown <- mk.test(mobiledesktop$porc, alternative = c("less"), continuity = TRUE)
aux<-data.frame(mobile = c(as.numeric(mobiletwo["p.value"]),as.numeric(mobileup["p.value"]),as.numeric(mobiledown["p.value"])),
               desktop = c(as.numeric(desktoptwo["p.value"]),as.numeric(desktopup["p.value"]),as.numeric(desktopdown["p.value"])),
               mobiledesktop = c(as.numeric(mobiledesktoptwo["p.value"]),as.numeric(mobiledesktopnup["p.value"]),as.numeric(mobiledesktopdown["p.value"])),
               row.names = c("twosided", "greater", "less"))
 
   print(kable(aux)) 
        cat("\n")
        
        
        
        
        
        
        
        
        
        
         cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
         cat("\n",  as.character( "0.5") ,"\n")
         
         
        print("<div align='center'>")
        cat ("\n\n#### Evolução dos desenvolvedores ao longo do tempo (Desktop Mobile)  \n( janela 24 semanas, iteracao de 4 semanas)\n")
        print("</div>")
        

  mobile <- mobile_bind%>% filter(prob==0.5)     
  desktop <-desktop_bind%>% filter(prob==0.5)  
  mobiledesktop <- desktopmobile_bind%>% filter(prob==0.5)   
 
   par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(mobile$iteracao,mobile$porc,col="red",type = "l",ylim = c(0,100),xlim=c(1,j), xlab = "Tempo (semanas)", ylab = "% de desenvolvedores",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  lines(desktop$iteracao,desktop$porc,col="green",type = "l" )
  lines(mobiledesktop$iteracao,mobiledesktop$porc,col="black",type = "l" )
  legend("top",c("Mobile", "Desktop", "Desktop Mobile"), col=c("red","green","black"),lty=1)

     if (length(mobile$porc)< 3){
    mobiletwo<-data.frame(p.value=99)
     mobileup<-data.frame(p.value=99)
      mobiledown<-data.frame(p.value=99)
  }else{
 mobiletwo <- mk.test(mobile$porc, alternative = c("two.sided"), continuity = TRUE)
 mobileup <- mk.test(mobile$porc, alternative = c("greater"), continuity = TRUE)
 mobiledown <- mk.test(mobile$porc, alternative = c("less"), continuity = TRUE)
  }
 desktoptwo <- mk.test(desktop$porc, alternative = c("two.sided"), continuity = TRUE)
 desktopup <- mk.test(desktop$porc, alternative = c("greater"), continuity = TRUE)
 desktopdown <- mk.test(desktop$porc, alternative = c("less"), continuity = TRUE)
 mobiledesktoptwo <- mk.test(mobiledesktop$porc, alternative = c("two.sided"), continuity = TRUE)
 mobiledesktopnup <- mk.test(mobiledesktop$porc, alternative = c("greater"), continuity = TRUE)
mobiledesktopdown <- mk.test(mobiledesktop$porc, alternative = c("less"), continuity = TRUE)
aux<-data.frame(mobile = c(as.numeric(mobiletwo["p.value"]),as.numeric(mobileup["p.value"]),as.numeric(mobiledown["p.value"])),
               desktop = c(as.numeric(desktoptwo["p.value"]),as.numeric(desktopup["p.value"]),as.numeric(desktopdown["p.value"])),
               mobiledesktop = c(as.numeric(mobiledesktoptwo["p.value"]),as.numeric(mobiledesktopnup["p.value"]),as.numeric(mobiledesktopdown["p.value"])),
               row.names = c("twosided", "greater", "less"))
 
   print(kable(aux)) 
        cat("\n")       
        
        
}
```

