---
title: "Caracterização do desenvolvimento de bibliotecas multiplataforma"
author: "Daniel Moreira, Rodrigo Rocha"
date: "August 31, 2017"
output:
  html_document: default
  pdf_document: default
---
<style type="text/css"> 
.table {    width: 40%; margin: 0px auto; }
.caption {    text-align: center; padding-bottom: 40px;}
.figure {width: 70%; margin: 0px auto;}
img {text-align: center; display: block;margin-left: auto;margin-right: auto; margin: 0px auto; }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)

```


# Resultados - Análise quantitativa
```{r results="asis", echo=FALSE,message=FALSE,warning=FALSE}




    

########
############################### QP1 ###################################
########  
  cat ("\n\n#### QP1 - Como é a distribuição de tarefas de manutenção entre o código independente e específico de plataforma?\n")

par(mar=c(5.1, 5, 4.1, 2.1)) 
 barplot(os_summary3$n_commit, names.arg =c("Cód. independente","Cód. específico","Ambos") ,  col=c("blue","orange","darkgreen"), ylab = "Número de modificações", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  #allegro
  legend(0.7, os_summary3$n_commit[1]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(1.9, os_summary3$n_commit[2]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(3.1, os_summary3$n_commit[3]/2 , "          ",yjust = 0.5,       xjust = 0.5)
  text(0.7,os_summary3$n_commit[1]/2,os_summary3$n_commit[1],cex=1.7)
  text(1.9,os_summary3$n_commit[2]/2,os_summary3$n_commit[2],cex=1.7)
  text(3.1,os_summary3$n_commit[3]/2,os_summary3$n_commit[3],cex=1.7)
#sdl
  legend(0.7, os_summary3$n_commit[1]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(1.9, os_summary3$n_commit[2]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(3.1, os_summary3$n_commit[3]/2 , "          ",yjust = 0.5,       xjust = 0.5)
  text(0.7,os_summary3$n_commit[1]/2,os_summary3$n_commit[1],cex=1.7)
  text(1.9,os_summary3$n_commit[2]/2,os_summary3$n_commit[2],cex=1.7)
  text(3.1,os_summary3$n_commit[3]/2,os_summary3$n_commit[3],cex=1.7)
  
  
  #ingles
  
  par(mar=c(5.1, 5, 4.1, 2.1)) 
 barplot(os_summary3$n_commit, names.arg =c("Independent code","Specific code","Both") ,  col=c("blue","orange","darkgreen"), ylab = "Number of commits", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  #allegro
  legend(0.7, os_summary3$n_commit[1]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(1.9, os_summary3$n_commit[2]/2, "          ",yjust = 0.5,       xjust = 0.5)
  legend(3.1, os_summary3$n_commit[3]/2 , "          ",yjust = 0.5,       xjust = 0.5)
  text(0.7,os_summary3$n_commit[1]/2,os_summary3$n_commit[1],cex=1.7)
  text(1.9,os_summary3$n_commit[2]/2,os_summary3$n_commit[2],cex=1.7)
  text(3.1,os_summary3$n_commit[3]/2,os_summary3$n_commit[3],cex=1.7)
  
  
  
  
  ########
  cat ("\n\n##### QP1.1 Qual plataforma é modificada com mais frequência?.\n")
    cat ("\n\n##### Contamos a quantidade de vezes que o código específico de cada plataforma é modificado.\n")
    par(mar=c(5.1, 5, 4.1, 2.1)) 
  barplot(os_summary$n_commit, names.arg = row.names(os_summary) ,col=rainbow(5), cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7, xlab = "Plataforma", ylab = "Número de modificações")
  #allegro
   legend(0.7,os_summary$n_commit[1]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
  legend(1.92,os_summary$n_commit[2],"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
   legend(3.1,os_summary$n_commit[3]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
    legend(4.3,os_summary$n_commit[4]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     legend(5.5,os_summary$n_commit[5]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     
     text(0.7,os_summary$n_commit[1]/2,os_summary$n_commit[1],cex=1.7)
     text(1.92,os_summary$n_commit[2],os_summary$n_commit[2],cex=1.7)
     text(3.1,os_summary$n_commit[3]/2,os_summary$n_commit[3],cex=1.7)
     text(4.3,os_summary$n_commit[4]/2,os_summary$n_commit[4],cex=1.7)
     text(5.5,os_summary$n_commit[5]/2,os_summary$n_commit[5],cex=1.7)
  
  #sdl
 legend(0.7,os_summary$n_commit[1]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
  legend(1.92,os_summary$n_commit[2]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
   legend(3.1,os_summary$n_commit[3]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
    legend(4.3,os_summary$n_commit[4]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     legend(5.5,os_summary$n_commit[5]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     
     text(0.7,os_summary$n_commit[1]/2,os_summary$n_commit[1],cex=1.7)
     text(1.92,os_summary$n_commit[2]/2,os_summary$n_commit[2],cex=1.7)
     text(3.1,os_summary$n_commit[3]/2,os_summary$n_commit[3],cex=1.7)
     text(4.3,os_summary$n_commit[4]/2,os_summary$n_commit[4],cex=1.7)
     text(5.5,os_summary$n_commit[5]/2,os_summary$n_commit[5],cex=1.7)

     
     
     #ingles
     
     
     
    par(mar=c(5.1, 5, 4.1, 2.1)) 
  barplot(os_summary$n_commit, names.arg = row.names(os_summary) ,col=rainbow(5), cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7, xlab = "Platform", ylab = "Number of commits")
  
  
########
###################################### QP2 ############################
########  

        cat ("\n\n##### QP2.2 - Qual a quantidade de plataformas que os desenvolvedores dão suporte?\n")
              cat ("\n\n##### Consideramos as plataformas Windows, Linux, macOS, iPhone e Android nesta contagem.\n")
      barplot(authors3_plats$n, names.arg = authors3_plats$n_platform, xlab = "Número de plataformas", ylab = "Número de desenvolvedores", col=heat.colors(5), main="Número de plataformas que os desenvolvedores dão suporte")
      
  par(mar=c(5.1, 5, 4.1, 2.1)) 
      barplot(authors3_plats$n, names.arg = authors3_plats$n_platform,  ylab = "Number of developers", col=heat.colors(5), xlab="Number of platforms",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7) 
        
        cat ("\n\n##### QP2.3 - Dos desenvolvedores   que trabalham com uma plataforma, como é a distribuição das plataformas?\n")
        barplot(devesp, main="Quantidade de desenvolvedores especialistas de cada plataforma", xlab = "Plataforma", col=rainbow(5), ylab = "Número de desenvolvedores")
       
        par(mar=c(5.1, 5, 4.1, 2.1))  
       barplot(devesp,names.arg = row.names(os_summary) ,col=rainbow(5), cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7, xlab = "Plataform", ylab = "Number of developers")
      #allegro
   legend(0.7,devesp[1]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
  legend(1.92,devesp[2]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
   legend(3.1,devesp[3]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 

     legend(5.5,devesp[5]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     
     text(0.7,devesp[1]/2,devesp[1],cex=1.7)
     text(1.92,devesp[2]/2,devesp[2],cex=1.7)
     text(3.1,devesp[3]/2,devesp[3],cex=1.7)

     text(5.5,devesp[5]/2,devesp[5],cex=1.7)
  
  #sdl
   legend(0.7,devesp[1]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
  legend(1.92,devesp[2]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
   legend(3.1,devesp[3]/2,"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
    legend(4.3,devesp[4],"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     legend(5.5,devesp[5],"      ",bg="white",yjust = 0.5,       xjust = 0.5) 
     
     text(0.7,devesp[1]/2,devesp[1],cex=1.7)
     text(1.92,devesp[2]/2,devesp[2],cex=1.7)
     text(3.1,devesp[3]/2,devesp[3],cex=1.7)
     text(4.3,devesp[4],devesp[4],cex=1.7)
     text(5.5,devesp[5],devesp[5],cex=1.7)
        cat ("\n\n##### QP4.3 - Dos desenvolvedores generalistas, qual a quantidade de plataformas que eles dão suporte?\n")
        print(kable(devgen))
  
 


########
########
########   
  cat ("\n\n#### Janela de 24 semanas\n")
 
        
         
    cat ("\n\n#### QP2.1 - A equipe de desenvolvimento de bibliotecas multiplataforma tende a tornar-se mais generalista ou especialista ao longo do tempo?\n")
    par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(dev_all_time24_2$iteracao, dev_all_time24_2$porcentage, col="darkslateblue", type="b",pch=20, xlab="Time (weeks)", ylim=c(0,100),ylab="% of generalists", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  
  z<-lm(porcentage~iteracao,data=dev_all_time24_2)
  abline(z,col="orange")

  
    par(mar=c(5.1, 5, 4.1, 2.1)) 
  plot(dev_all_time24_2$iteracao, dev_all_time24_2$porcentage, col="darkslateblue", type="b",pch=20, xlab="Tempo (semanas)", ylim=c(0,100),ylab="% de generalistas", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
  
  z<-lm(porcentage~iteracao,data=dev_all_time24_2)
  abline(z,col="orange")
    
  
  
    cat ("\n\n#### QP3.1 - Os desenvolvedores de bibliotecas multiplataforma tendem a especializar-se em dispositivos desktop ou mobile ao longo do tempo?\n")
    
    par(mar=c(5.1, 5, 4.1, 2.1)) 
   plot(devicetype_time24_2$iteracao, devicetype_time24_2$porcentage, col="darkslateblue", type="b",pch=20, xlab="Tempo (semanas)",ylim=c(0,100), ylab="Porcentagem",cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)    z<-lm(porcentage~iteracao,data=devicetype_time24_2)
  abline(z,col="orange")
   
   
   
       par(mar=c(5.1, 5, 4.1, 2.1)) 
   plot(devicetype_time24_2$iteracao, devicetype_time24_2$porcentage, col="darkslateblue", type="b",pch=20, xlab="Time (weeks)",ylim=c(0,100), ylab="Percentage") 
```



