---
title: "limiares"
output: html_document
---

```{r setup, include=FALSE, results="asis", echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, warn.conflicts = FALSE)
library(venn)
library(stringr)
library(knitr)
library(ggplot2)
library(trend)
# Create variable 'log'  that contains the paths of the scripts and workspaces (.RData)
  source("./paths.R")

dist_cipcep<-data.frame()
dist_cipcep2<-data.frame(row.names = c("cip","cep","cipcep"))
```



```{r results="asis", echo=FALSE,message=FALSE,warning=FALSE}
for (it in 1:length(logs$sistema)){
  aux<-it
  #cat("  \n###",  as.character( logs$sistema[it] ) ,"\n")
  rm(list = ls()[!ls() %in% c("logs","it","dist_cipcep2","dist_cipcep")])
  #source(as.character(logs$caminho[it]) , verbose=FALSE)
  #source( './analise.R', echo=FALSE, verbose=FALSE, prompt.echo=FALSE)
  load (as.character(logs$ws_analise[it]))

        cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")
        
  x<-data.frame (porc = os_summary3$n_commit*100/sum(os_summary3$n_commit),
                 tipo = rownames(os_summary3),
                 sistema = c(as.character(logs$sistema[it]),as.character(logs$sistema[it]),as.character(logs$sistema[it])))
  dist_cipcep<-rbind(dist_cipcep,x)
       
  
x<-data.frame (os_summary3$n_commit*100/sum(os_summary3$n_commit))
colnames(x)<- as.character(logs$sistema[it])
dist_cipcep2<-cbind(dist_cipcep2,x)

   # Shapiro-Wilk test:
    #    Null hypothesis: the data are normally distributed
    #   Alternative hypothesis: the data are not normally distributed
    # if the p-value is greater than the significance level 0.05 implying that the distribution of the data are not significantly different from normal distribtion. In other words, we can assume the normality.
    
  #One sample t test http://www.sthda.com/english/wiki/one-sample-t-test-in-r
    # H0:m=μ
    # Ha:m≠μ (different)
   # assumptions
      # small sample ok
      # normality teste
    #if p-value which is less than the significance level alpha = 0.05, We can conclude that the they are significantly different 

x<-os_summary3$n_commit*100/sum(os_summary3$n_commit)
    shapiro <-data.frame(parametros=c("SHAPIRO",unlist(shapiro.test(x))))
    t<- data.frame(parametros=c("T.TEST",unlist(t.test(x))))
        #x: a numeric vector containing your data values
        #mu: the theoretical mean. Default is 0 but you can change it.
        #alternative: the alternative hypothesis. Allowed value is one of “two.sided” (default), “greater” or “less”.
    testes<-rbind(shapiro,t)
    barplot(x, names.arg =c("Independente","Específico","Ambos") , ylim=c(0,100), xlab = "Tipo", col=c("blue","orange","darkgreen"), ylab = "Porcentagem", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
    print(kable(testes))
    rm(shapiro,t,testes)

}

   cat("\n\n\n")

p<-ggplot(dist_cipcep) +
  aes(x = sistema, y = porc, fill = tipo) +
  geom_col()+
  ylim(0,100)+
  theme(text = element_text(size=16))+
  labs(fill = "Tipo", x=element_blank(), y="Porcentagem")
  scale_fill_brewer(palette="Dark2",labels  = c("CIP e CEP","CEP","CIP"))
  
   
print(p)
 cat("\n\n\n")
# kruskal.test
# null hypothesis - identical populations (p.value > 0.05)
# alternative - different (p.value < 0.05)


kruskaltest<- data.frame(kruskal=unlist(kruskal.test(porc ~ tipo, data = dist_cipcep) ))
print(kable(kruskaltest))

 cat("\n\n\n")
kruskaltest<- data.frame(kruskal=unlist(kruskal.test(porc ~ sistema, data = dist_cipcep) ))
print(kable(kruskaltest))


```

