---
title: "limiares"
output: html_document
---

```{r setup, include=FALSE, results="asis", echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, warn.conflicts = FALSE)
library(venn)
library(stringr)
library(knitr)
library(ggplot2)
library(trend)
# Create variable 'log'  that contains the paths of the scripts and workspaces (.RData)
  source("./paths.R")

z<-data.frame(row.names=c("Especialista","Generalista"))
z1<-data.frame()
z2<-data.frame()
w<-data.frame(row.names=c("Desktop","Mobile","Desktop e Mobile"))
w1<-data.frame()
w2<-data.frame()
w3<-data.frame()

ge<-data.frame()
dm<-data.frame()
saida_plat_total<-data.frame()
```



```{r results="asis", echo=FALSE,message=FALSE,warning=FALSE}
for (it in 1:length(logs$sistema)){

    rm(list = ls()[!ls() %in% c("logs","it","z","w","z1","z2","w1","w2","w3","ge","dm","saida_plat_total")])
      #source(as.character(logs$caminho[it]) )
      load (as.character(logs$ws_analise[it]))


        cat("\n\n####",  as.character( logs$sistema[it] ) ,"\n")

  x<-saida_plat%>% 
      filter(prob==0.00)
  
  xx<-x %>% mutate(sistema=as.character( logs$sistema[it] ) )
  saida_plat_total<-rbind(saida_plat_total,xx)
  
  
    ndev<-max(saida_plat$ndev)  
    gen<-nrow((filter(x, tipo == "gen")))  
    esp<-nrow((filter(x, tipo == "esp")))
    x<-data.frame(count=c(gen,esp),tipo=c("gen","esp"),sistema= c(as.character(logs$sistema[it]),as.character(logs$sistema[it])))
    xxx<-x
   # x<-x%>% mutate(sistema=as.character(logs$sistema[it]))
    ge<-rbind(ge,x)
    x<-x%>%select(count)
    z<-cbind(z,x)
    z1<- rbind(z1,gen)
    z2<- rbind(z2,esp)

    
    
# Discutions about ttest and sd for two observations        
# https://math.stackexchange.com/questions/1584608/is-it-valid-to-calculate-standard-deviation-for-n-2
# https://stats.stackexchange.com/questions/230171/is-it-meaningful-to-calculate-standard-deviation-of-two-numbers
         s<- data.frame (parametros=sd(x$count), row.names = "sd")
         t<- data.frame(parametros=c("T.TEST",unlist(t.test(x))))
         testes<-rbind(s,t)
         
         barplot(x$count, names.arg =c("Especialista","Generalista") ,  xlab = "Tipo", col=c("blue","orange"), ylab = "Quantidade", cex.names = 1.7,cex.axis = 1.7,cex.lab=1.7)
         cat("\n\n\n")  
         print(kable(testes)) 
         
         cat("\n\n\n") 
if( gen >4 & esp >4)
{
  r <- xtabs(~ sistema + tipo, data=xx)
  #xxx<-xtabs(xxx)
  quiquadrado<- data.frame(quiquadrado=unlist(chisq.test(r )))
  print(kable(quiquadrado))
  cat("\n\n\n") 
  #rm("r","quiquadrado")
}


}
  cat("\n\n\n") 
  
colnames(z1) <- "Generalista"
colnames(z2) <- "Especialista"


Sistemas <- as.character(logs$sistema)

###################
##################
#Generalista e especialista
###################
###################
      dados1<-data.frame(Sistemas,z1,z2)
      #pt
     ggplot(ge) +
       aes(x = sistema, y = count, fill = tipo) +
       geom_col()+
      # ylim(0,100)+
       theme(text = element_text(size=16))+
       labs(fill = "Tipo", x=element_blank(), y="Quantidade")+
       scale_fill_brewer(palette="Set1",labels  = c("Especialista","Generalista"))

  cat("\n\n\n") 

   wilcoxtest<- data.frame(unlist(wilcox.test(count ~ tipo, data=ge) ))
   print(kable(wilcoxtest))


cat("\n\n\n") 
kruskaltest<- data.frame(kruskal=unlist(kruskal.test(count ~ sistema, data = ge) ))
print(kable(kruskaltest))


# Comparando distribuições dos sistemas

#t <- table(saida_plat_total$sistema,saida_plat_total$tipo)
r <- xtabs(~ sistema + tipo, data=saida_plat_total)
#print(kable(t))
cat("\n\n\n") 
mosaicplot(r)





#Valor-p ≤ α: as variáveis apresentam uma associação estatisticamente significativa (rejeite H0)
#    Se o valor-p for menor ou igual ao nível de significância, rejeite a hipótese nula e conclua que há uma associação estatisticamente significativa entre as variáveis. 
#Valor-p > α: não é possível concluir que as variáveis estão associadas (não deve rejeitar H0)
#    Se o valor-p for maior do que o nível de significância, você não deve rejeitar a hipótese nula porque não há evidências suficientes para concluir que as variáveis estão associadas. 
    
    
cat("\n\n\n") 
fishertest<- data.frame(fishertest=unlist(fisher.test(r)))
print(kable(fishertest))

```

